MetaMask/website

- README.md
Looping this into: https://github.com/MetaMask/website/pull/124#issue-1230820936
> Updated git url

- yarn.lock
👾 **Describe The Sumarry:** 
in the case of an (authentication) error, the error object returned by the library contains the original request of the user, which may include the plaintext password the user entered. If the error object is exposed or logged without modification, the application risks password exposure.
```js
trimUserDetails: trimUserDetails
```
🥷 **According CVeScores:** 
CVE-2020-5263
[CWE-522](https://cwe.mitre.org/data/definitions/522.html)
> Fixed Information disclosure through error object in auth0.js

- .github/ISSUE_TEMPLATE/metamask.md
Creating an issue template to guide and monitor when issues are created on the Metamask repo
> Creating Initial Issue Type

- src/components/PortfolioPage/Map/PortfolioMap.js
- src/components/PortfolioPage/Portfolio.data.js
> Updated embed URLs for YouTube videos

- src/pages/portfolio.js
- yarn.lock
This PR adds custom title and description meta tags for the /portfolio page.
> SEO Meta Tags for /portfolio page

- src/components/PortfolioPage/Map/Canvas/Gl/imog/Scene/Image/index.js
This PR brings in a fix for this issue:
> Fixed offset texture in intro

- src/components/HeroContainer.js
Ticket:
Note: Publish this Contentful entry after you merge the PR: https://app.contentful.com/spaces/9sy2a0egs6zh/environments/master/entries/ilTg6PVWUzx5wIEkrEjgk
> Add MetaMask portfolio button on MetaMask home hero

- gatsby-config.js
- gatsby-node.js
- legal/cookies.mdx
- legal/privacy-policy.mdx
- legal/terms-of-use.mdx
- package.json
- src/components/MarkdownPageBody.js
- src/templates/MarkdownPageLayout.js
- yarn.lock
Legal pages will be generated based on content of following files:
- legal/cookies.mdx
- legal/privacy-policy.mdx
- legal/terms-of-use.mdx
The files above will be in sync with legal.consensys.io via GitHub Actions defined here: https://github.com/Consensys/legal-pages/pull/27
> Improve generating legal pages

- src/templates/AuthorProfileLayout.js
> fix(author): image id

- src/components/DevReleaseNotes.js
- src/components/Image.js
- src/components/Logo/LogoImage.js
Consensys/metamask-website/issues/608
> fix: SEO - Properly Size and Add Dimensions to Images

- src/components/Footer.js
- src/components/Header.js
- src/hooks/useCountry.js
- src/lib/utils/filterMenuPaths.js
#	src/components/Footer.js
#	src/components/Header.js
#	src/lib/config.mjs
> feat: add temporary geoblocking for uk visitors

- src/components/MetaMaskBlogPull.js
Fixes https://github.com/Consensys/metamask-website/issues/652
> fix: pull slug for developers news

- src/components/CTA.js
- src/components/Card.js
- src/components/Card/CardBenefit.js
- src/components/Card/CardDelegationFeature.js
- src/components/Faq.js
- src/components/HeroContainer.js
- src/components/RichText.js
- src/components/layout.scss
- src/lib/theme.js
- static/images/icon-arrow-right.svg
See https://github.com/Consensys/metamask-website/issues/650
> Add delegation toolkit page

- src/components/RichText.js
See https://github.com/Consensys/metamask-website/issues/662
> feat: remove quotation marks from custom quote

- src/hooks/useLangDetect.js
See https://github.com/Consensys/metamask-website/issues/672
> fix: support htmllang values that include region

- src/components/CTA.js
Implements https://github.com/Consensys/metamask-website/issues/705
> feat: add general mm download cta experiment

- src/components/CTA.js
Implements https://github.com/Consensys/metamask-website/issues/706
> feat: add home portfolio cta experiment

- src/components/CTA.js
Implements https://github.com/Consensys/metamask-website/issues/706
> fix: emit download cta click event for download cta header flag

- src/components/CTA.js
Implements https://github.com/Consensys/metamask-website/issues/
> fix: use treatment text in case of deep links as well

- gatsby-node.js
- src/components/UKApprovalNotice.js
- src/lib/config.mjs
- src/templates/ContentfulDownloadLayout.js
- src/templates/ContentfulLayout.js
- src/templates/ContentfulNewsCategoryLayout.js
Implements https://github.com/Consensys/metamask-website/issues/638
> Add UK approved copy support

- src/components/CTA.js
- src/components/HeroContainer.js
- src/components/layout.scss
See https://github.com/Consensys/metamask-website/issues/722
> Add home hero portfolio ab test

- src/lib/config.mjs
https://github.com/Consensys/metamask-website/issues/724
> feat: 724 geoblock swap blogpost
